# Generated by Django 3.2.14 on 2023-07-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
                ('sem', models.IntegerField()),
                ('files', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='subjects',
        ),
    ]
